-- Migration to add missing columns to gst_invoices and invoices in PostgreSQL
ALTER TABLE gst_invoices 
ADD COLUMN IF NOT EXISTS sender_product_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS receiver_product_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS product_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS unit VARCHAR(20),
ADD COLUMN IF NOT EXISTS quantity NUMERIC DEFAULT 1,
ADD COLUMN IF NOT EXISTS pdf_url TEXT;

ALTER TABLE invoices 
ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS customer_gstin VARCHAR(50),
ADD COLUMN IF NOT EXISTS taxable_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS irn TEXT,
ADD COLUMN IF NOT EXISTS ack_no VARCHAR(100),
ADD COLUMN IF NOT EXISTS ack_date VARCHAR(100),
ADD COLUMN IF NOT EXISTS signed_qr TEXT,
ADD COLUMN IF NOT EXISTS pdf_url TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_invoices_inv_num ON invoices(invoice_number);
CREATE UNIQUE INDEX IF NOT EXISTS idx_gst_invoices_inv_num ON gst_invoices(invoice_number);
