const db = require('../db/connection');
const { getIO } = require('../socketServer');

/**
 * Real-time Integration between CLIKS Business (Merchant ERP) and CLIKS (Customer Application)
 * Triggered immediately after a Sales Invoice is successfully generated by a merchant.
 */
async function processCustomerInvoiceIntegration({ createdInvoice, merchantUserId }) {
    if (!createdInvoice) {
        console.error('[SYNC ERROR] Synchronization Failed: createdInvoice is null or undefined.');
        return;
    }

    const now = new Date().toISOString();
    const invoiceId = createdInvoice.id;
    const invoiceNumber = createdInvoice.invoice_number;
    const clientEmail = createdInvoice.client_email ? String(createdInvoice.client_email).trim() : null;
    const clientName = createdInvoice.client_name || 'Customer';

    console.log(`[SYNC LOG] Invoice Saved: #${invoiceNumber} (ID: ${invoiceId})`);

    try {
        // 1. Resolve Customer Email & Customer ID
        let clientEmail = createdInvoice.client_email ? String(createdInvoice.client_email).trim() : null;
        let customerId = createdInvoice.customer_id || null;

        if (!clientEmail || !customerId) {
            const custRow = await db.prepare(`
                SELECT id, email, name FROM business_customers 
                WHERE user_id = ? 
                  AND (
                      (id IS NOT NULL AND id = ?)
                      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(?)))
                      OR (name IS NOT NULL AND LOWER(TRIM(name)) = LOWER(TRIM(?)))
                  )
                ORDER BY id DESC LIMIT 1
            `).get(merchantUserId, customerId || 0, clientEmail || '', clientName || '');

            if (custRow) {
                if (custRow.id && !customerId) customerId = custRow.id;
                if (custRow.email && !clientEmail) {
                    clientEmail = String(custRow.email).trim();
                    try {
                        await db.prepare('UPDATE business_invoices SET client_email = ?, customer_id = ? WHERE id = ?').run(clientEmail, customerId, invoiceId);
                        createdInvoice.client_email = clientEmail;
                        createdInvoice.customer_id = customerId;
                    } catch (e) {}
                }
            }
        }

        if (!clientEmail && !customerId) {
            console.log(`[SYNC NOTICE] No customer email or ID could be resolved for invoice #${invoiceNumber}. Synchronization skipped.`);
            return;
        }

        const emailLower = clientEmail ? clientEmail.toLowerCase().trim() : '';

        // 2. Customer-Business Connection Check: Must match customer_id OR customer_email / website_user_id with status = 'accepted'/'connected'
        let connRecord = await db.prepare(`
            SELECT * FROM customer_connections
            WHERE business_id = ? AND (
                (business_customer_id IS NOT NULL AND business_customer_id = ?)
                ${emailLower ? 'OR (customer_email IS NOT NULL AND LOWER(TRIM(customer_email)) = ?)' : ''}
            )
        `).get(...(emailLower ? [merchantUserId, customerId || 0, emailLower] : [merchantUserId, customerId || 0]));

        const statusLower = connRecord ? String(connRecord.status).toLowerCase() : '';
        if (!connRecord || (statusLower !== 'accepted' && statusLower !== 'connected')) {
            console.log(`[SYNC NOTICE] Connection status is ${connRecord ? connRecord.status : 'UNCONNECTED'} (not accepted or connected) for customer with merchant ${merchantUserId}. Invoice #${invoiceNumber} synchronization skipped.`);
            return;
        }

        // Match website customer user account
        let customerUser = null;
        if (connRecord.website_user_id) {
            customerUser = await db.prepare('SELECT * FROM users WHERE id = ?').get(connRecord.website_user_id);
        }

        if (!customerUser && emailLower) {
            customerUser = await db.prepare('SELECT * FROM users WHERE LOWER(email) = ?').get(emailLower);
        }

        // If no matching CLIKS user account exists, auto-create customer user record so purchase history, loyalty, merchant card, and invoice sync immediately
        if (!customerUser && emailLower) {
            console.log(`[SYNC LOG] Auto-registering new customer user for ${emailLower}...`);
            const defaultName = clientName || emailLower.split('@')[0];
            try {
                const insertUserRes = await db.prepare(`
                    INSERT INTO users (username, email, password_hash, role, receive_data, receiveData, loyalty_points, created_at, updated_at)
                    VALUES (?, ?, 'sso-managed', 'user', 1, 1, 0, ?, ?)
                `).run(defaultName, emailLower, now, now);
                customerUser = await db.prepare('SELECT * FROM users WHERE id = ?').get(insertUserRes.lastInsertRowid);
            } catch (err) {
                console.error('[SYNC ERROR] Error auto-creating customer user:', err.message);
                customerUser = await db.prepare('SELECT * FROM users WHERE LOWER(email) = ?').get(emailLower);
            }
        }

        if (!customerUser) {
            console.error(`[SYNC ERROR] Synchronization Failed: Customer user could not be found or created.`);
            return;
        }

        // Ensure connection record is updated with website_user_id and customer_id
        try {
            await db.prepare(`
                UPDATE customer_connections 
                SET website_user_id = ?, business_customer_id = ?
                WHERE id = ?
            `).run(customerUser.id, customerId || connRecord.business_customer_id, connRecord.id);
        } catch (e) {}

        console.log(`[SYNC LOG] Customer Found: ${customerUser.email} (ID: ${customerUser.id})`);

        // 3. Two-Way Consent Check: Customer Receive Data Permission
        let customerReceiveData = true; // Default = YES
        if (customerUser.receive_data !== undefined && customerUser.receive_data !== null) {
            customerReceiveData = customerUser.receive_data === true || customerUser.receive_data === 1 || String(customerUser.receive_data).toUpperCase() === 'YES' || String(customerUser.receive_data) === 'true';
        } else if (customerUser.receiveData !== undefined && customerUser.receiveData !== null) {
            customerReceiveData = customerUser.receiveData === true || customerUser.receiveData === 1 || String(customerUser.receiveData).toUpperCase() === 'YES' || String(customerUser.receiveData) === 'true';
        } else if (customerUser.settings) {
            try {
                const parsedSettings = typeof customerUser.settings === 'string' ? JSON.parse(customerUser.settings) : customerUser.settings;
                if (parsedSettings.receiveData !== undefined) {
                    customerReceiveData = parsedSettings.receiveData === true || parsedSettings.receiveData === 1 || String(parsedSettings.receiveData).toUpperCase() === 'YES' || String(parsedSettings.receiveData) === 'true';
                } else if (parsedSettings.receive_data !== undefined) {
                    customerReceiveData = parsedSettings.receive_data === true || parsedSettings.receive_data === 1 || String(parsedSettings.receive_data).toUpperCase() === 'YES' || String(parsedSettings.receive_data) === 'true';
                }
            } catch (e) {}
        }

        if (!customerReceiveData) {
            console.log(`[SYNC NOTICE] Customer ${clientEmail} has Receive Data = NO. Two-way consent not met. Invoice #${invoiceNumber} will NOT be synchronized.`);
            return;
        }

        console.log(`[SYNC LOG] Synchronization Started for Invoice #${invoiceNumber}`);

        // Fetch Merchant Info
        const merchantUser = await db.prepare(
            'SELECT id, username, business_name, email FROM users WHERE id = ?'
        ).get(merchantUserId);

        const merchantName = (merchantUser && (merchantUser.business_name || merchantUser.username)) 
            ? (merchantUser.business_name || merchantUser.username) 
            : 'CLIKS Merchant';
        const merchantEmail = (merchantUser && merchantUser.email) ? merchantUser.email : '';
        const merchantLogo = (merchantUser && (merchantUser.logo_url || merchantUser.business_logo)) ? (merchantUser.logo_url || merchantUser.business_logo) : '';

        const numTotal = parseFloat(createdInvoice.total_amount) || 0;
        const numTax = parseFloat(createdInvoice.tax_amount) || 0;
        const numDiscount = parseFloat(createdInvoice.discount_amount) || 0;
        const numAmount = parseFloat(createdInvoice.amount) || (numTotal - numTax + numDiscount);
        const numPaid = parseFloat(createdInvoice.paid_amount) || 0;
        const numDue = parseFloat(createdInvoice.due_amount) || Math.max(0, numTotal - numPaid);
        const numRoundOff = parseFloat(createdInvoice.round_off) || 0;

        let paymentStatus = createdInvoice.payment_status;
        if (!paymentStatus) {
            paymentStatus = numPaid >= numTotal ? 'Paid' : (numPaid > 0 ? 'Partially Paid' : 'Unpaid');
        }
        const invoiceStatus = createdInvoice.status || 'Active';
        const invoiceDate = createdInvoice.created_at || createdInvoice.due_date || now;
        const dueDate = createdInvoice.due_date || '';
        const invoiceType = createdInvoice.invoice_type || 'GST';
        const paymentMode = createdInvoice.payment_mode || 'Cash';
        const upiId = createdInvoice.upi_id || '';
        const bankAccountId = createdInvoice.bank_account_id ? String(createdInvoice.bank_account_id) : '';
        const customerGstin = createdInvoice.client_gstin || '';
        const shippingAddress = createdInvoice.shipping_address || '';

        // Save invoice items into `invoice_items` table
        let items = createdInvoice.items;
        if (typeof items === 'string') {
            try { items = JSON.parse(items); } catch (e) { items = []; }
        }
        if (Array.isArray(items) && items.length > 0 && invoiceId) {
            try {
                await db.prepare('DELETE FROM invoice_items WHERE invoice_id = ?').run(invoiceId);
            } catch (e) {}

            for (const item of items) {
                const prodName = item.product_name || item.name || item.description || 'Item';
                const desc = item.description || item.product_name || item.name || 'Item';
                const hsn = item.hsn_code || item.sku || item.hsn_sac || item.sku_hsn || '';
                const qty = parseFloat(item.quantity) || 1;
                const unit = item.unit || 'Pcs';
                const rate = parseFloat(item.price || item.rate || item.unit_price) || 0;
                const discPct = parseFloat(item.discount_percent) || 0;
                const discAmt = parseFloat(item.discount_amount) || 0;
                const gstPct = parseFloat(item.tax_rate || item.gst_percentage || item.gst_rate) || 0;
                const gstAmt = parseFloat(item.tax_amount || item.gst_amount) || (qty * rate * (gstPct / 100));
                const amt = parseFloat(item.total || item.amount) || ((qty * rate) - discAmt + gstAmt);

                try {
                    await db.prepare(`
                        INSERT INTO invoice_items (
                            invoice_id, product_name, description, hsn_code, quantity, unit,
                            rate, price, discount_percent, discount_amount, tax_rate, tax_amount, amount, total, created_at
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    `).run(
                        invoiceId, prodName, desc, hsn, qty, unit,
                        rate, rate, discPct, discAmt, gstPct, gstAmt, amt, amt, now
                    );
                } catch (err) {
                    console.error('[SYNC WARNING] Error inserting invoice_item:', err.message);
                }
            }
        }

        // Calculate Loyalty Points
        const earnedPoints = Math.max(0, Math.floor(numTotal / 100));
        const redeemedPoints = Math.max(0, parseInt(createdInvoice.redeemed_points) || 0);
        const netPointsChange = earnedPoints - redeemedPoints;

        // Formatted Purchased Products array
        const formattedItems = (items || []).map(item => {
            const desc = item.description || item.product_name || item.name || 'Item';
            const qty = parseFloat(item.quantity) || 1;
            const price = parseFloat(item.price || item.rate || item.unit_price) || 0;
            const discPct = parseFloat(item.discount_percent) || 0;
            const discAmt = parseFloat(item.discount_amount) || 0;
            const gstPct = parseFloat(item.tax_rate || item.gst_percentage || item.gst_rate) || 0;
            const gstAmt = parseFloat(item.tax_amount || item.gst_amount) || (qty * price * (gstPct / 100));
            const total = parseFloat(item.total || item.amount) || ((qty * price) - discAmt + gstAmt);

            return {
                product_name: item.product_name || desc,
                description: desc,
                sku_hsn: item.hsn_code || item.sku || item.hsn_sac || '',
                quantity: qty,
                unit: item.unit || 'Pcs',
                unit_price: price,
                discount_percent: discPct,
                discount_amount: discAmt,
                gst_percent: gstPct,
                gst_amount: gstAmt,
                item_total: total
            };
        });
        const itemsJson = JSON.stringify(formattedItems);

        // 4. Create/update Purchase History record (Duplicate Prevention)
        const existingRecord = await db.prepare(
            'SELECT id FROM customer_purchase_history WHERE invoice_number = ? AND merchant_business_id = ?'
        ).get(invoiceNumber, merchantUserId);

        let insertedHistId = null;

        if (existingRecord) {
            insertedHistId = existingRecord.id;
            await db.prepare(`
                UPDATE customer_purchase_history SET
                    invoice_type = ?, invoice_date = ?, due_date = ?, invoice_status = ?,
                    payment_status = ?, payment_mode = ?, upi_id = ?, bank_account_id = ?,
                    merchant_name = ?, merchant_email = ?, merchant_logo = ?,
                    customer_name = ?, customer_email = ?, customer_gstin = ?, shipping_address = ?,
                    subtotal = ?, total_amount = ?, gst = ?, discount = ?, round_off = ?,
                    net_amount = ?, paid_amount = ?, due_amount = ?,
                    points_earned = ?, points_redeemed = ?, net_points_added = ?,
                    invoice_id = ?, items = ?, updated_at = ?
                WHERE id = ?
            `).run(
                invoiceType, invoiceDate, dueDate, invoiceStatus,
                paymentStatus, paymentMode, upiId, bankAccountId,
                merchantName, merchantEmail, merchantLogo,
                clientName, customerUser.email || clientEmail, customerGstin, shippingAddress,
                numAmount, numTotal, numTax, numDiscount, numRoundOff,
                numTotal, numPaid, numDue,
                earnedPoints, redeemedPoints, netPointsChange,
                invoiceId, itemsJson, now,
                existingRecord.id
            );
        } else {
            const insertParams = [
                invoiceNumber, invoiceType, invoiceDate, dueDate, invoiceStatus,
                paymentStatus, paymentMode, upiId, bankAccountId,
                merchantUserId, merchantName, merchantEmail, merchantLogo,
                customerUser.id, clientName, customerUser.email || clientEmail, customerGstin, shippingAddress,
                numAmount, numTotal, numTax, numDiscount, numRoundOff,
                numTotal, numPaid, numDue,
                earnedPoints, redeemedPoints, netPointsChange, 1, 1,
                invoiceId, itemsJson, now, now
            ];

            const histRes = await db.prepare(`
                INSERT INTO customer_purchase_history (
                    invoice_number, invoice_type, invoice_date, due_date, invoice_status,
                    payment_status, payment_mode, upi_id, bank_account_id,
                    merchant_business_id, merchant_name, merchant_email, merchant_logo,
                    customer_user_id, customer_name, customer_email, customer_gstin, shipping_address,
                    subtotal, total_amount, gst, discount, round_off,
                    net_amount, paid_amount, due_amount,
                    points_earned, points_redeemed, net_points_added, sendToCustomerHistory, sendPurchaseHistoryToCustomer,
                    invoice_id, items, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            `).run(...insertParams);

            insertedHistId = histRes?.lastInsertRowid || histRes?.id;

            try {
                await db.prepare(`
                    INSERT INTO purchase_history (
                        invoice_number, invoice_type, invoice_date, due_date, invoice_status,
                        payment_status, payment_mode, upi_id, bank_account_id,
                        merchant_business_id, merchant_name, merchant_email, merchant_logo,
                        customer_user_id, customer_name, customer_email, customer_gstin, shipping_address,
                        subtotal, total_amount, gst, discount, round_off,
                        net_amount, paid_amount, due_amount,
                        points_earned, points_redeemed, net_points_added, sendToCustomerHistory, sendPurchaseHistoryToCustomer,
                        invoice_id, items, created_at, updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                `).run(...insertParams);
            } catch (e) {}
        }

        console.log(`[SYNC LOG] Purchase History Inserted: ID #${insertedHistId || 'OK'}`);

        // 5. Create or Update Merchant Summary Card table (merchant_summary)
        try {
            const existingMerchantSummary = await db.prepare(`
                SELECT * FROM merchant_summary WHERE merchant_business_id = ? AND customer_user_id = ?
            `).get(merchantUserId, customerUser.id);

            if (existingMerchantSummary) {
                await db.prepare(`
                    UPDATE merchant_summary 
                    SET merchant_name = ?,
                        merchant_email = ?,
                        merchant_logo = ?,
                        customer_email = ?,
                        purchases_count = purchases_count + 1,
                        total_spent = total_spent + ?,
                        points_earned = points_earned + ?,
                        points_redeemed = points_redeemed + ?,
                        net_points = net_points + ?,
                        last_purchase_date = ?,
                        updated_at = ?
                    WHERE merchant_business_id = ? AND customer_user_id = ?
                `).run(
                    merchantName, merchantEmail, merchantLogo, customerUser.email || clientEmail,
                    numTotal, earnedPoints, redeemedPoints, netPointsChange, invoiceDate, now,
                    merchantUserId, customerUser.id
                );
            } else {
                await db.prepare(`
                    INSERT INTO merchant_summary (
                        merchant_business_id, merchant_name, merchant_email, merchant_logo,
                        customer_user_id, customer_email, purchases_count, total_spent,
                        points_earned, points_redeemed, net_points, last_purchase_date, created_at, updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?, ?, ?, ?, ?, ?)
                `).run(
                    merchantUserId, merchantName, merchantEmail, merchantLogo,
                    customerUser.id, customerUser.email || clientEmail, numTotal,
                    earnedPoints, redeemedPoints, netPointsChange, invoiceDate, now, now
                );
            }
            console.log(`[SYNC LOG] Merchant Summary Updated for Merchant #${merchantUserId}`);
        } catch (merchantSummaryErr) {
            console.error(`[SYNC WARNING] Failed to update merchant_summary: ${merchantSummaryErr.message}`);
        }

        // 6. Update Customer's Loyalty Wallet in central DB
        if (earnedPoints > 0 || redeemedPoints > 0) {
            const existingWallet = await db.prepare(
                'SELECT * FROM customer_loyalty_wallets WHERE user_id = ?'
            ).get(customerUser.id);

            if (existingWallet) {
                const newBal = Math.max(0, (existingWallet.points_balance || 0) + netPointsChange);
                await db.prepare(`
                    UPDATE customer_loyalty_wallets 
                    SET points_balance = ?,
                        total_earned = total_earned + ?,
                        total_redeemed = total_redeemed + ?,
                        updated_at = ?
                    WHERE user_id = ?
                `).run(newBal, earnedPoints, redeemedPoints, now, customerUser.id);
            } else {
                const initBal = Math.max(0, netPointsChange);
                await db.prepare(`
                    INSERT INTO customer_loyalty_wallets (user_id, points_balance, total_earned, total_redeemed, created_at, updated_at)
                    VALUES (?, ?, ?, ?, ?, ?)
                `).run(customerUser.id, initBal, earnedPoints, redeemedPoints, now, now);
            }

            if (earnedPoints > 0) {
                await db.prepare(`
                    INSERT INTO customer_loyalty_transactions (user_id, invoice_number, merchant_name, points_earned, points_redeemed, description, created_at)
                    VALUES (?, ?, ?, ?, 0, ?, ?)
                `).run(
                    customerUser.id, invoiceNumber, merchantName, earnedPoints,
                    `Earned ${earnedPoints} pts from purchase #${invoiceNumber} at ${merchantName}`, now
                );
            }

            if (redeemedPoints > 0) {
                await db.prepare(`
                    INSERT INTO customer_loyalty_transactions (user_id, invoice_number, merchant_name, points_earned, points_redeemed, description, created_at)
                    VALUES (?, ?, ?, 0, ?, ?, ?)
                `).run(
                    customerUser.id, invoiceNumber, merchantName, redeemedPoints,
                    `Redeemed ${redeemedPoints} pts on purchase #${invoiceNumber} at ${merchantName}`, now
                );
            }

            try {
                const curUserObj = await db.prepare('SELECT loyalty_points FROM users WHERE id = ?').get(customerUser.id);
                const updatedUserPts = Math.max(0, ((curUserObj && curUserObj.loyalty_points) || 0) + netPointsChange);
                await db.prepare(`
                    UPDATE users SET loyalty_points = ? WHERE id = ?
                `).run(updatedUserPts, customerUser.id);
            } catch (e) {}

            try {
                const curCrm = await db.prepare('SELECT loyalty_points FROM business_customers WHERE LOWER(email) = ? AND user_id = ?').get(emailLower, merchantUserId);
                if (curCrm) {
                    const updatedCrmPts = Math.max(0, (curCrm.loyalty_points || 0) + netPointsChange);
                    await db.prepare(`
                        UPDATE business_customers 
                        SET loyalty_points = ?,
                            total_spent = COALESCE(total_spent, 0) + ?,
                            updated_at = ?
                        WHERE LOWER(email) = ? AND user_id = ?
                    `).run(updatedCrmPts, numTotal, now, emailLower, merchantUserId);
                }
            } catch (e) {}

            console.log(`[SYNC LOG] Loyalty Points Saved: +${earnedPoints} pts for Customer #${customerUser.id}`);
        }

        // 7. Insert/Update Active Integration Record (active_integrations)
        try {
            const existingIntegration = await db.prepare(`
                SELECT * FROM active_integrations WHERE merchant_business_id = ? AND customer_user_id = ?
            `).get(merchantUserId, customerUser.id);

            if (existingIntegration) {
                await db.prepare(`
                    UPDATE active_integrations 
                    SET status = 'Active',
                        last_synced_at = ?,
                        updated_at = ?
                    WHERE id = ?
                `).run(now, now, existingIntegration.id);
            } else {
                await db.prepare(`
                    INSERT INTO active_integrations (
                        user_id, integration_name, integration_type, merchant_business_id,
                        merchant_name, customer_user_id, customer_email, status, last_synced_at, created_at, updated_at
                    ) VALUES (?, 'CLIKS Business Invoice Sync', 'merchant_sync', ?, ?, ?, ?, 'Active', ?, ?, ?)
                `).run(
                    customerUser.id, merchantUserId, merchantName, customerUser.id,
                    customerUser.email || clientEmail, now, now, now
                );
            }
            console.log(`[SYNC LOG] Active Integrations Record Inserted for Customer #${customerUser.id}`);
        } catch (activeIntegErr) {
            console.error(`[SYNC WARNING] Failed to insert active_integrations: ${activeIntegErr.message}`);
        }

        // 8. Create a notification informing the customer that a new purchase has been added
        const notifTitle = 'New Purchase Recorded';
        const notifMessage = `New purchase of ₹${numTotal.toLocaleString('en-IN')} recorded from ${merchantName} (Invoice #${invoiceNumber}). Earned ${earnedPoints} loyalty points!`;
        
        await db.prepare(`
            INSERT INTO notifications (
                sender_id, receiver_id, user_id, title, message, type, is_read, link, created_at
            ) VALUES (?, ?, ?, ?, ?, 'Purchase', 0, '/purchases', ?)
        `).run(merchantUserId, customerUser.id, customerUser.id, notifTitle, notifMessage, now);

        // Dispatches WebSocket event for real-time notification
        try {
            const io = getIO();
            if (io) {
                io.emit('customer-purchase-added', {
                    customerId: customerUser.id,
                    customerEmail: customerUser.email,
                    invoiceNumber,
                    merchantName,
                    netAmount: numTotal,
                    loyaltyPointsEarned: earnedPoints,
                    timestamp: now
                });
                io.to(`user_${customerUser.id}`).emit('new-notification', {
                    title: notifTitle,
                    message: notifMessage,
                    link: '/purchases',
                    created_at: now
                });
            }
        } catch (socketErr) {}

        console.log(`[SYNC LOG] Synchronization Completed Successfully for Invoice #${invoiceNumber}`);

    } catch (error) {
        console.error(`[SYNC ERROR] Synchronization Failed for Invoice #${invoiceNumber}:`, error.message, error.stack);
    }
}

/**
 * On-demand sync of all connected customer purchases across all connected store instances.
 */
async function syncConnectedCustomerPurchases(userId, userEmail) {
    if (!userId && !userEmail) return;
    const emailLower = userEmail ? String(userEmail).trim().toLowerCase() : '';

    try {
        // Find all connected business IDs for this customer from customer_connections table
        const connections = await db.prepare(`
            SELECT DISTINCT business_id, business_customer_id, customer_email 
            FROM customer_connections 
            WHERE (website_user_id = ? ${emailLower ? 'OR LOWER(customer_email) = ?' : ''})
              AND (LOWER(status) = 'accepted' OR LOWER(status) = 'connected')
        `).all(...(emailLower ? [userId, emailLower] : [userId]));

        if (!connections || connections.length === 0) return;

        for (const conn of connections) {
            const merchantUserId = conn.business_id;
            const bCustId = conn.business_customer_id;
            const connEmail = conn.customer_email ? String(conn.customer_email).trim().toLowerCase() : emailLower;

            let custName = '';
            if (bCustId) {
                try {
                    const bc = await db.prepare('SELECT name, email FROM business_customers WHERE id = ?').get(bCustId);
                    if (bc && bc.name) custName = bc.name.trim().toLowerCase();
                } catch (e) {}
            }

            const matchingInvoices = await db.prepare(`
                SELECT * FROM business_invoices 
                WHERE user_id = ? 
                  AND (
                      (client_email IS NOT NULL AND LOWER(client_email) = ?)
                      ${connEmail ? 'OR (client_email IS NOT NULL AND LOWER(client_email) = ?)' : ''}
                      ${bCustId ? 'OR (bank_account_id IS NOT NULL AND bank_account_id = ?)' : ''}
                      ${custName ? 'OR (client_name IS NOT NULL AND LOWER(client_name) = ?)' : ''}
                  )
                ORDER BY id ASC
            `).all(
                merchantUserId,
                emailLower,
                ...(connEmail ? [connEmail] : []),
                ...(bCustId ? [bCustId] : []),
                ...(custName ? [custName] : [])
            );

            for (const inv of (matchingInvoices || [])) {
                await processCustomerInvoiceIntegration({
                    createdInvoice: inv,
                    merchantUserId: inv.user_id
                });
            }
        }
    } catch (err) {
        console.error('[SYNC ERROR] Auto-sync connected customer purchases failed:', err.message);
    }
}

module.exports = {
    processCustomerInvoiceIntegration,
    syncConnectedCustomerPurchases
};
