const db = require('../db/connection');
const { getIO } = require('../socketServer');

/**
 * Real-time Integration between CLIKS Business (Merchant ERP) and CLIKS (Customer Application)
 * Triggered immediately after a Sales Invoice is successfully generated by a merchant.
 */
async function processCustomerInvoiceIntegration({ createdInvoice, merchantUserId }) {
    if (!createdInvoice) return;

    try {
        const now = new Date().toISOString();
        const invoiceId = createdInvoice.id;
        const invoiceNumber = createdInvoice.invoice_number;
        const clientEmail = createdInvoice.client_email ? String(createdInvoice.client_email).trim() : null;
        const clientName = createdInvoice.client_name || 'Customer';

        // 1. Save all invoice items into `invoice_items` table if present and not already saved
        let items = createdInvoice.items;
        if (typeof items === 'string') {
            try { items = JSON.parse(items); } catch (e) { items = []; }
        }
        if (Array.isArray(items) && items.length > 0 && invoiceId) {
            for (const item of items) {
                const desc = item.description || item.name || item.product_name || 'Item';
                const qty = parseFloat(item.quantity) || 1;
                const rate = parseFloat(item.rate || item.price || item.unit_price) || 0;
                const amt = parseFloat(item.amount || item.total) || (qty * rate);

                try {
                    await db.prepare(`
                        INSERT INTO invoice_items (invoice_id, description, quantity, rate, amount)
                        VALUES (?, ?, ?, ?, ?)
                    `).run(invoiceId, desc, qty, rate, amt);
                } catch (err) {
                    // Ignore duplicate insertion or table error
                }
            }
        }

        // If no email was entered in the invoice, continue normal workflow quietly
        if (!clientEmail) return;

        // 2. Check whether the customer's email entered in the invoice exists as a registered CLIKS user (case-insensitive)
        const emailLower = clientEmail.toLowerCase();
        const customerUser = await db.prepare(
            'SELECT * FROM users WHERE LOWER(email) = ?'
        ).get(emailLower);

        // If no matching CLIKS account exists, continue normal invoice workflow without any changes
        if (!customerUser) {
            console.log(`[Customer Integration] No registered CLIKS user for ${clientEmail}. Continuing standard workflow.`);
            return;
        }

        // 3. Matching CLIKS user account exists! Fetch Merchant Info
        const merchantUser = await db.prepare(
            'SELECT id, username, business_name, email FROM users WHERE id = ?'
        ).get(merchantUserId);

        const merchantName = (merchantUser && (merchantUser.business_name || merchantUser.username)) 
            ? (merchantUser.business_name || merchantUser.username) 
            : 'CLIKS Merchant';

        const numTotal = parseFloat(createdInvoice.total_amount) || 0;
        const numTax = parseFloat(createdInvoice.tax_amount) || 0;
        const numDiscount = parseFloat(createdInvoice.discount_amount) || 0;
        const numAmount = parseFloat(createdInvoice.amount) || (numTotal - numTax + numDiscount);
        const numPaid = parseFloat(createdInvoice.paid_amount) || 0;

        let paymentStatus = createdInvoice.payment_status;
        if (!paymentStatus) {
            paymentStatus = numPaid >= numTotal ? 'Paid' : (numPaid > 0 ? 'Partially Paid' : 'Unpaid');
        }
        const invoiceStatus = createdInvoice.status || 'Active';
        const invoiceDate = createdInvoice.created_at || createdInvoice.due_date || now;

        // 4. Automatically create a Purchase History record for that customer
        const historyParams = [
            invoiceNumber, merchantName, merchantUserId, customerUser.id,
            clientName, customerUser.email || clientEmail, invoiceDate, numAmount, numTax,
            numDiscount, numTotal, paymentStatus, invoiceStatus, invoiceId,
            typeof createdInvoice.items === 'string' ? createdInvoice.items : JSON.stringify(items || []),
            now, now
        ];

        await db.prepare(`
            INSERT INTO customer_purchase_history (
                invoice_number, merchant_name, merchant_business_id, customer_user_id,
                customer_name, customer_email, invoice_date, total_amount, gst,
                discount, net_amount, payment_status, invoice_status, invoice_id, items,
                created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        `).run(...historyParams);

        try {
            await db.prepare(`
                INSERT INTO purchase_history (
                    invoice_number, merchant_name, merchant_business_id, customer_user_id,
                    customer_name, customer_email, invoice_date, total_amount, gst,
                    discount, net_amount, payment_status, invoice_status, invoice_id, items,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            `).run(...historyParams);
        } catch (e) {}

        // 5. Automatically calculate Loyalty Points according to existing business rules
        // Rule: Earn 1 point per 100 units of net bill amount (in active currency)
        const earnedPoints = Math.max(0, Math.floor(numTotal / 100));
        const redeemedPoints = Math.max(0, parseInt(createdInvoice.redeemed_points) || 0);
        const netPointsChange = earnedPoints - redeemedPoints;

        // 6. Update Customer's Loyalty Wallet in central DB
        if (earnedPoints > 0 || redeemedPoints > 0) {
            const existingWallet = await db.prepare(
                'SELECT * FROM customer_loyalty_wallets WHERE user_id = ?'
            ).get(customerUser.id);

            if (existingWallet) {
                const newBal = Math.max(0, (existingWallet.points_balance || 0) + netPointsChange);
                await db.prepare(`
                    UPDATE customer_loyalty_wallets 
                    SET points_balance = ?,
                        total_earned = total_earned + ?,
                        total_redeemed = total_redeemed + ?,
                        updated_at = ?
                    WHERE user_id = ?
                `).run(newBal, earnedPoints, redeemedPoints, now, customerUser.id);
            } else {
                const initBal = Math.max(0, netPointsChange);
                await db.prepare(`
                    INSERT INTO customer_loyalty_wallets (user_id, points_balance, total_earned, total_redeemed, created_at, updated_at)
                    VALUES (?, ?, ?, ?, ?, ?)
                `).run(customerUser.id, initBal, earnedPoints, redeemedPoints, now, now);
            }

            if (earnedPoints > 0) {
                await db.prepare(`
                    INSERT INTO customer_loyalty_transactions (user_id, invoice_number, merchant_name, points_earned, points_redeemed, description, created_at)
                    VALUES (?, ?, ?, ?, 0, ?, ?)
                `).run(
                    customerUser.id, invoiceNumber, merchantName, earnedPoints,
                    `Earned ${earnedPoints} pts from purchase #${invoiceNumber} at ${merchantName}`, now
                );
            }

            if (redeemedPoints > 0) {
                await db.prepare(`
                    INSERT INTO customer_loyalty_transactions (user_id, invoice_number, merchant_name, points_earned, points_redeemed, description, created_at)
                    VALUES (?, ?, ?, 0, ?, ?, ?)
                `).run(
                    customerUser.id, invoiceNumber, merchantName, redeemedPoints,
                    `Redeemed ${redeemedPoints} pts on purchase #${invoiceNumber} at ${merchantName}`, now
                );
            }

            try {
                const curUserObj = await db.prepare('SELECT loyalty_points FROM users WHERE id = ?').get(customerUser.id);
                const updatedUserPts = Math.max(0, ((curUserObj && curUserObj.loyalty_points) || 0) + netPointsChange);
                await db.prepare(`
                    UPDATE users SET loyalty_points = ? WHERE id = ?
                `).run(updatedUserPts, customerUser.id);
            } catch (e) {}

            try {
                const curCrm = await db.prepare('SELECT loyalty_points FROM business_customers WHERE LOWER(email) = ? AND user_id = ?').get(emailLower, merchantUserId);
                if (curCrm) {
                    const updatedCrmPts = Math.max(0, (curCrm.loyalty_points || 0) + netPointsChange);
                    await db.prepare(`
                        UPDATE business_customers 
                        SET loyalty_points = ?,
                            total_spent = COALESCE(total_spent, 0) + ?,
                            updated_at = ?
                        WHERE LOWER(email) = ? AND user_id = ?
                    `).run(updatedCrmPts, numTotal, now, emailLower, merchantUserId);
                }
            } catch (e) {}
        }

        // 7. Create a notification informing the customer that a new purchase has been added
        const notifTitle = 'New Purchase Recorded';
        const notifMessage = `New purchase of ₹${numTotal.toLocaleString('en-IN')} recorded from ${merchantName} (Invoice #${invoiceNumber}). Earned ${earnedPoints} loyalty points!`;
        
        await db.prepare(`
            INSERT INTO notifications (
                sender_id, receiver_id, user_id, title, message, type, is_read, link, created_at
            ) VALUES (?, ?, ?, ?, ?, 'Purchase', 0, '/purchases', ?)
        `).run(merchantUserId, customerUser.id, customerUser.id, notifTitle, notifMessage, now);

        // Dispatches WebSocket event for real-time notification
        try {
            const io = getIO();
            if (io) {
                io.emit('customer-purchase-added', {
                    customerId: customerUser.id,
                    customerEmail: customerUser.email,
                    invoiceNumber,
                    merchantName,
                    netAmount: numTotal,
                    loyaltyPointsEarned: earnedPoints,
                    timestamp: now
                });
                io.to(`user_${customerUser.id}`).emit('new-notification', {
                    title: notifTitle,
                    message: notifMessage,
                    link: '/purchases',
                    created_at: now
                });
            }
        } catch (socketErr) {
            // Socket errors do not abort database updates
        }

        console.log(`[Customer Integration] Real-time sync complete for CLIKS Customer #${customerUser.id} on invoice #${invoiceNumber}`);

    } catch (error) {
        console.error('[Customer Integration] Error in real-time invoice sync:', error);
    }
}

module.exports = {
    processCustomerInvoiceIntegration
};
