const db = require('../db/connection');
const { getIO } = require('../socketServer');

/**
 * Real-time Integration between CLIKS Business (Merchant ERP) and CLIKS (Customer Application)
 * Triggered immediately after a Sales Invoice is successfully generated by a merchant.
 */
async function processCustomerInvoiceIntegration({ createdInvoice, merchantUserId }) {
    if (!createdInvoice) return;

    try {
        const now = new Date().toISOString();
        const invoiceId = createdInvoice.id;
        const invoiceNumber = createdInvoice.invoice_number;
        const clientEmail = createdInvoice.client_email ? String(createdInvoice.client_email).trim() : null;
        const clientName = createdInvoice.client_name || 'Customer';

        // 1. Save all invoice items into `invoice_items` table if present and not already saved
        let items = createdInvoice.items;
        if (typeof items === 'string') {
            try { items = JSON.parse(items); } catch (e) { items = []; }
        }
        if (Array.isArray(items) && items.length > 0 && invoiceId) {
            try {
                await db.prepare('DELETE FROM invoice_items WHERE invoice_id = ?').run(invoiceId);
            } catch (e) {}

            for (const item of items) {
                const prodName = item.product_name || item.name || item.description || 'Item';
                const desc = item.description || item.product_name || item.name || 'Item';
                const hsn = item.hsn_code || item.sku || item.hsn_sac || item.sku_hsn || '';
                const qty = parseFloat(item.quantity) || 1;
                const unit = item.unit || 'Pcs';
                const rate = parseFloat(item.price || item.rate || item.unit_price) || 0;
                const discPct = parseFloat(item.discount_percent) || 0;
                const discAmt = parseFloat(item.discount_amount) || 0;
                const gstPct = parseFloat(item.tax_rate || item.gst_percentage || item.gst_rate) || 0;
                const gstAmt = parseFloat(item.tax_amount || item.gst_amount) || (qty * rate * (gstPct / 100));
                const amt = parseFloat(item.total || item.amount) || ((qty * rate) - discAmt + gstAmt);

                try {
                    await db.prepare(`
                        INSERT INTO invoice_items (
                            invoice_id, product_name, description, hsn_code, quantity, unit,
                            rate, price, discount_percent, discount_amount, tax_rate, tax_amount, amount, total, created_at
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    `).run(
                        invoiceId, prodName, desc, hsn, qty, unit,
                        rate, rate, discPct, discAmt, gstPct, gstAmt, amt, amt, now
                    );
                } catch (err) {
                    console.error('[Customer Integration] Error inserting invoice_item:', err);
                }
            }
        }

        // Check sendToCustomerHistory rule: Synchronization is only allowed if sendToCustomerHistory is true
        const isSendToCustomer = createdInvoice.sendToCustomerHistory !== undefined
            ? (createdInvoice.sendToCustomerHistory === true || createdInvoice.sendToCustomerHistory === 1 || createdInvoice.sendToCustomerHistory === 'true' || createdInvoice.sendToCustomerHistory === '1')
            : true;

        if (!isSendToCustomer) {
            console.log(`[Customer Integration] sendToCustomerHistory is false for invoice #${invoiceNumber}. Skipping synchronization to customer CLIKS account.`);
            return;
        }

        // If no email was entered in the invoice, continue normal workflow quietly
        if (!clientEmail) return;

        // 2. Check whether the customer's email entered in the invoice exists as a registered CLIKS user (case-insensitive)
        const emailLower = clientEmail.toLowerCase();
        const customerUser = await db.prepare(
            'SELECT * FROM users WHERE LOWER(email) = ?'
        ).get(emailLower);

        // If no matching CLIKS account exists, continue normal invoice workflow without any changes
        if (!customerUser) {
            console.log(`[Customer Integration] No registered CLIKS user for ${clientEmail}. Continuing standard workflow.`);
            return;
        }

        // 3. Matching CLIKS user account exists! Fetch Merchant Info
        const merchantUser = await db.prepare(
            'SELECT id, username, business_name, email FROM users WHERE id = ?'
        ).get(merchantUserId);

        const merchantName = (merchantUser && (merchantUser.business_name || merchantUser.username)) 
            ? (merchantUser.business_name || merchantUser.username) 
            : 'CLIKS Merchant';
        const merchantEmail = (merchantUser && merchantUser.email) ? merchantUser.email : '';
        const merchantLogo = (merchantUser && (merchantUser.logo_url || merchantUser.business_logo)) ? (merchantUser.logo_url || merchantUser.business_logo) : '';

        const numTotal = parseFloat(createdInvoice.total_amount) || 0;
        const numTax = parseFloat(createdInvoice.tax_amount) || 0;
        const numDiscount = parseFloat(createdInvoice.discount_amount) || 0;
        const numAmount = parseFloat(createdInvoice.amount) || (numTotal - numTax + numDiscount);
        const numPaid = parseFloat(createdInvoice.paid_amount) || 0;
        const numDue = parseFloat(createdInvoice.due_amount) || Math.max(0, numTotal - numPaid);
        const numRoundOff = parseFloat(createdInvoice.round_off) || 0;

        let paymentStatus = createdInvoice.payment_status;
        if (!paymentStatus) {
            paymentStatus = numPaid >= numTotal ? 'Paid' : (numPaid > 0 ? 'Partially Paid' : 'Unpaid');
        }
        const invoiceStatus = createdInvoice.status || 'Active';
        const invoiceDate = createdInvoice.created_at || createdInvoice.due_date || now;
        const dueDate = createdInvoice.due_date || '';
        const invoiceType = createdInvoice.invoice_type || 'GST';
        const paymentMode = createdInvoice.payment_mode || 'Cash';
        const upiId = createdInvoice.upi_id || '';
        const bankAccountId = createdInvoice.bank_account_id ? String(createdInvoice.bank_account_id) : '';
        const customerGstin = createdInvoice.client_gstin || '';
        const shippingAddress = createdInvoice.shipping_address || '';

        // 5. Automatically calculate Loyalty Points according to existing business rules
        const earnedPoints = Math.max(0, Math.floor(numTotal / 100));
        const redeemedPoints = Math.max(0, parseInt(createdInvoice.redeemed_points) || 0);
        const netPointsChange = earnedPoints - redeemedPoints;

        // Formatted Purchased Products array
        const formattedItems = (items || []).map(item => {
            const desc = item.description || item.product_name || item.name || 'Item';
            const qty = parseFloat(item.quantity) || 1;
            const price = parseFloat(item.price || item.rate || item.unit_price) || 0;
            const discPct = parseFloat(item.discount_percent) || 0;
            const discAmt = parseFloat(item.discount_amount) || 0;
            const gstPct = parseFloat(item.tax_rate || item.gst_percentage || item.gst_rate) || 0;
            const gstAmt = parseFloat(item.tax_amount || item.gst_amount) || (qty * price * (gstPct / 100));
            const total = parseFloat(item.total || item.amount) || ((qty * price) - discAmt + gstAmt);

            return {
                product_name: item.product_name || desc,
                description: desc,
                sku_hsn: item.hsn_code || item.sku || item.hsn_sac || '',
                quantity: qty,
                unit: item.unit || 'Pcs',
                unit_price: price,
                discount_percent: discPct,
                discount_amount: discAmt,
                gst_percent: gstPct,
                gst_amount: gstAmt,
                item_total: total
            };
        });
        const itemsJson = JSON.stringify(formattedItems);

        // 4. Automatically create/update Purchase History record (Duplicate Prevention)
        const existingRecord = await db.prepare(
            'SELECT id FROM customer_purchase_history WHERE invoice_number = ? AND merchant_business_id = ?'
        ).get(invoiceNumber, merchantUserId);

        if (existingRecord) {
            await db.prepare(`
                UPDATE customer_purchase_history SET
                    invoice_type = ?, invoice_date = ?, due_date = ?, invoice_status = ?,
                    payment_status = ?, payment_mode = ?, upi_id = ?, bank_account_id = ?,
                    merchant_name = ?, merchant_email = ?, merchant_logo = ?,
                    customer_name = ?, customer_email = ?, customer_gstin = ?, shipping_address = ?,
                    subtotal = ?, total_amount = ?, gst = ?, discount = ?, round_off = ?,
                    net_amount = ?, paid_amount = ?, due_amount = ?,
                    points_earned = ?, points_redeemed = ?, net_points_added = ?,
                    invoice_id = ?, items = ?, updated_at = ?
                WHERE id = ?
            `).run(
                invoiceType, invoiceDate, dueDate, invoiceStatus,
                paymentStatus, paymentMode, upiId, bankAccountId,
                merchantName, merchantEmail, merchantLogo,
                clientName, customerUser.email || clientEmail, customerGstin, shippingAddress,
                numAmount, numTotal, numTax, numDiscount, numRoundOff,
                numTotal, numPaid, numDue,
                earnedPoints, redeemedPoints, netPointsChange,
                invoiceId, itemsJson, now,
                existingRecord.id
            );
        } else {
            const insertParams = [
                invoiceNumber, invoiceType, invoiceDate, dueDate, invoiceStatus,
                paymentStatus, paymentMode, upiId, bankAccountId,
                merchantUserId, merchantName, merchantEmail, merchantLogo,
                customerUser.id, clientName, customerUser.email || clientEmail, customerGstin, shippingAddress,
                numAmount, numTotal, numTax, numDiscount, numRoundOff,
                numTotal, numPaid, numDue,
                earnedPoints, redeemedPoints, netPointsChange, 1,
                invoiceId, itemsJson, now, now
            ];

            await db.prepare(`
                INSERT INTO customer_purchase_history (
                    invoice_number, invoice_type, invoice_date, due_date, invoice_status,
                    payment_status, payment_mode, upi_id, bank_account_id,
                    merchant_business_id, merchant_name, merchant_email, merchant_logo,
                    customer_user_id, customer_name, customer_email, customer_gstin, shipping_address,
                    subtotal, total_amount, gst, discount, round_off,
                    net_amount, paid_amount, due_amount,
                    points_earned, points_redeemed, net_points_added, sendToCustomerHistory,
                    invoice_id, items, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            `).run(...insertParams);

            try {
                await db.prepare(`
                    INSERT INTO purchase_history (
                        invoice_number, invoice_type, invoice_date, due_date, invoice_status,
                        payment_status, payment_mode, upi_id, bank_account_id,
                        merchant_business_id, merchant_name, merchant_email, merchant_logo,
                        customer_user_id, customer_name, customer_email, customer_gstin, shipping_address,
                        subtotal, total_amount, gst, discount, round_off,
                        net_amount, paid_amount, due_amount,
                        points_earned, points_redeemed, net_points_added, sendToCustomerHistory,
                        invoice_id, items, created_at, updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                `).run(...insertParams);
            } catch (e) {}
        }

        // 6. Update Customer's Loyalty Wallet in central DB
        if (earnedPoints > 0 || redeemedPoints > 0) {
            const existingWallet = await db.prepare(
                'SELECT * FROM customer_loyalty_wallets WHERE user_id = ?'
            ).get(customerUser.id);

            if (existingWallet) {
                const newBal = Math.max(0, (existingWallet.points_balance || 0) + netPointsChange);
                await db.prepare(`
                    UPDATE customer_loyalty_wallets 
                    SET points_balance = ?,
                        total_earned = total_earned + ?,
                        total_redeemed = total_redeemed + ?,
                        updated_at = ?
                    WHERE user_id = ?
                `).run(newBal, earnedPoints, redeemedPoints, now, customerUser.id);
            } else {
                const initBal = Math.max(0, netPointsChange);
                await db.prepare(`
                    INSERT INTO customer_loyalty_wallets (user_id, points_balance, total_earned, total_redeemed, created_at, updated_at)
                    VALUES (?, ?, ?, ?, ?, ?)
                `).run(customerUser.id, initBal, earnedPoints, redeemedPoints, now, now);
            }

            if (earnedPoints > 0) {
                await db.prepare(`
                    INSERT INTO customer_loyalty_transactions (user_id, invoice_number, merchant_name, points_earned, points_redeemed, description, created_at)
                    VALUES (?, ?, ?, ?, 0, ?, ?)
                `).run(
                    customerUser.id, invoiceNumber, merchantName, earnedPoints,
                    `Earned ${earnedPoints} pts from purchase #${invoiceNumber} at ${merchantName}`, now
                );
            }

            if (redeemedPoints > 0) {
                await db.prepare(`
                    INSERT INTO customer_loyalty_transactions (user_id, invoice_number, merchant_name, points_earned, points_redeemed, description, created_at)
                    VALUES (?, ?, ?, 0, ?, ?, ?)
                `).run(
                    customerUser.id, invoiceNumber, merchantName, redeemedPoints,
                    `Redeemed ${redeemedPoints} pts on purchase #${invoiceNumber} at ${merchantName}`, now
                );
            }

            try {
                const curUserObj = await db.prepare('SELECT loyalty_points FROM users WHERE id = ?').get(customerUser.id);
                const updatedUserPts = Math.max(0, ((curUserObj && curUserObj.loyalty_points) || 0) + netPointsChange);
                await db.prepare(`
                    UPDATE users SET loyalty_points = ? WHERE id = ?
                `).run(updatedUserPts, customerUser.id);
            } catch (e) {}

            try {
                const curCrm = await db.prepare('SELECT loyalty_points FROM business_customers WHERE LOWER(email) = ? AND user_id = ?').get(emailLower, merchantUserId);
                if (curCrm) {
                    const updatedCrmPts = Math.max(0, (curCrm.loyalty_points || 0) + netPointsChange);
                    await db.prepare(`
                        UPDATE business_customers 
                        SET loyalty_points = ?,
                            total_spent = COALESCE(total_spent, 0) + ?,
                            updated_at = ?
                        WHERE LOWER(email) = ? AND user_id = ?
                    `).run(updatedCrmPts, numTotal, now, emailLower, merchantUserId);
                }
            } catch (e) {}
        }

        // 7. Create a notification informing the customer that a new purchase has been added
        const notifTitle = 'New Purchase Recorded';
        const notifMessage = `New purchase of ₹${numTotal.toLocaleString('en-IN')} recorded from ${merchantName} (Invoice #${invoiceNumber}). Earned ${earnedPoints} loyalty points!`;
        
        await db.prepare(`
            INSERT INTO notifications (
                sender_id, receiver_id, user_id, title, message, type, is_read, link, created_at
            ) VALUES (?, ?, ?, ?, ?, 'Purchase', 0, '/purchases', ?)
        `).run(merchantUserId, customerUser.id, customerUser.id, notifTitle, notifMessage, now);

        // Dispatches WebSocket event for real-time notification
        try {
            const io = getIO();
            if (io) {
                io.emit('customer-purchase-added', {
                    customerId: customerUser.id,
                    customerEmail: customerUser.email,
                    invoiceNumber,
                    merchantName,
                    netAmount: numTotal,
                    loyaltyPointsEarned: earnedPoints,
                    timestamp: now
                });
                io.to(`user_${customerUser.id}`).emit('new-notification', {
                    title: notifTitle,
                    message: notifMessage,
                    link: '/purchases',
                    created_at: now
                });
            }
        } catch (socketErr) {
            // Socket errors do not abort database updates
        }

        console.log(`[Customer Integration] Real-time sync complete for CLIKS Customer #${customerUser.id} on invoice #${invoiceNumber}`);

    } catch (error) {
        console.error('[Customer Integration] Error in real-time invoice sync:', error);
    }
}

module.exports = {
    processCustomerInvoiceIntegration
};
